# Generated by Django 3.0.4 on 2020-03-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_cursos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
