# Generated by Django 3.0.4 on 2020-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_auto_20200306_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
