# Generated by Django 3.0.4 on 2020-03-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_auto_20200306_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
